### PR TITLE
[style]: revamp the benefits section

### PR DESCRIPTION
**Pull request by Hemashree21**
Resolved issue #37 

image

image

@harmeetsingh11 please check and let me know if any changes are required

### CODE REVIEW

**Comment by harmeetsingh11** [comment]
@Hemashree21 The design and color scheme looks great implemented in vanilla CSS. However, since the project uses Tailwind CSS, it's better to stick with that. I appreciate your efforts. Could you please rewrite the same code using Tailwind CSS?

**Comment by Hemashree21** [comment]
Sure sir no problem

**Comment by Hemashree21** [comment]
image

image

@harmeetsingh11 I wrote the code in Tailwind sir but the background on hover is plain now. Please check sir.

**Comment by harmeetsingh11** [comment]
@Hemashree21 it looks good. Congrats your PR is merged🎉

**Comment by Hemashree21** [comment]
> @Hemashree21 it looks good. Congrats your PR is merged🎉

Thankyou!

**Pull request merged**
