### PR TITLE
Fix: Enable Mobile Navigation Bar Toggle on Hamburger Menu Click

### PR DESCRIPTION
**Pull request by saurabhgdeshmukh**
image

### CODE REVIEW

**Comment by saurabhgdeshmukh** [comment]
@harmeetsingh11 please check fixed issue

**Comment by harmeetsingh11** [comment]
@saurabhgdeshmukh Thank you for your pull request submission. However, there are a couple of issues that need attention in your PR:

- The menu items disappeared in the desktop version.
- The background color of the hero section and code refactor section disappeared.

Additionally, there's no need to manually import tailwind.css; it's already set up in the project.

Please review these issues and consider making the necessary commits to your existing pull request or submit a fresh pull request.

Let me know if you have any questions or need further clarification.

### Screenshots

**Comment by saurabhgdeshmukh** [comment]
@harmeetsingh11 please review the changes and check your discord.

**Comment by harmeetsingh11** [comment]
LGTM. I'm merging this PR.

**Pull request merged**
