### PR TITLE
 Refactoring part pushed upside and text part reduced to bottom

### PR DESCRIPTION
**Pull request by Devesh-Daku**
Resolved issue #6 
Please have a look

### CODE REVIEW

**Comment by harmeetsingh11** [comment]
@Devesh-Daku, thank you for submitting the pull request. Could you please implement the following changes?

1. Swap the positions of the "Benefits Section" and the "Code Refactor Section."
2. Replace the "Read More" text with "Try it" and link it to the "Code Refactor" section.

If you have any questions or need further clarification, please feel free to reach out. I've attached the screenshot for your reference.

Thank you!

**Comment by Devesh-Daku** [comment]
Okay

**Comment by Devesh-Daku** [comment]
Should I keep the paragraph there?

**Comment by harmeetsingh11** [comment]
> Should I keep the paragraph there?

The hero section will stay as it is, just swap the benefits and code refactor sections.

**Pull request closed without merging**
